### ISSUE TITLE
problem on python3

### ISSUE THREAD

**Issue by bdfy** [zhihu/redis-shard#31]
redis_shard/hashring.py

hash_methods = {
    'crc32': zlib.crc32,
    'md5': lambda x: long(md5(x).hexdigest(), 16),
    'sha1': lambda x: long(sha1(x).hexdigest(), 16),
}

in python3 error : 

NameError: name 'long' is not defined

**Comment by youngking** [comment]
fix in https://github.com/zhihu/redis-shard/commit/8ea0b7548b80493a1bf1cd4e5a38f059688b0b1e
