### ISSUE TITLE
是否支持多组sentinel

### ISSUE THREAD

**Issue by raingolee** [zhihu/redis-shard#32]
是否可以在配置中填写多组sentinel，例如有两组sentinel分别是A，B

那么是否支持在这两组sentinel之间做shard

redis-shard/redis_shard/shard.py 43:

```
if sentinel:                                                                                                    
    sentinel = Sentinel(sentinel['hosts'], socket_timeout=get('socket_time',1))
```
好像是不支持的

**Comment by wayhome** [comment]
这里的行为和官方的 redis-py 一致，填写的多组 sentinel 需要是在一个集群中的。

**Comment by raingolee** [comment]
也就是说当一组sentinel 内存不够的时候，也没法scale了是吧？是否可以改进一下支持多组sentinel，谢谢

**Comment by wayhome** [comment]
没遇到这种场景，一组sentinel 内存不够是什么规模？ 我们一组 sentinel 管理几十个 redis 切片实例对，上 T 内存不是问题。

**Comment by raingolee** [comment]
恩。我知道了，谢谢哈，我关了这个issue
