### ISSUE TITLE
"URL schema" configuration method does not work

### ISSUE THREAD

**Issue by ebrensi** [zhihu/redis-shard#35]
The documentation for redis-shard indicates that we should be able to instantiate an instance using Redis urls, as in 
- URL schema::
    [
        'redis://127.0.0.1:10000/0?name=node1',
        'redis://127.0.0.1:11000/0?name=node2&max_connections=50',
        'redis://127.0.0.1:12000/0?name=node3'
    ] 

which does not work.  First of all in  `RedisShardAPI()`, the `__init__` method expects `servers` to be a list of dictionaries, each having a `name` field.
 ```
def __init__(self, servers, hash_method='crc32', sentinel=None, strict_redis=False):
        ...
        for server_config in servers:
            name = server_config.pop('name')
            server_config["max_connections"] = int(server_config.get("max_connections", 100))
            if name in self.connections:
                raise ValueError("server's name config must be unique")
            if sentinel:
                self.connections[name] = SentinelRedis(sentinel, name)
            elif strict_redis:
                self.connections[name] = redis.StrictRedis(**server_config)
            else:
                self.connections[name] = redis.Redis(**server_config)
            ...
```
Secondly, `redis.Redis(**server_config)` does not work because the list elements are not dictionaries, and even if they were dictionaries with a `name` field, that instantiation method does not accept a `url` parameter.  We need to use [`redis.Redis.from_url(...)`](https://github.com/andymccurdy/redis-py/blob/25c46abdebbf60c599e6b9fcd7a4532bd8272a55/redis/client.py#L461-L488)

**Comment by wayhome** [comment]
hi,  there is a `format_servers` method which will convert the url schemas  to a list of dict. 

https://github.com/zhihu/redis-shard/blob/0d08c9e3f7105f7a1cfb248f58685518bb856642/redis_shard/shard.py#L44

**Comment by ebrensi** [comment]
oh, I see.  I didn't include the name parameter in the url.  thanks!
